GET http://localhost:8080/hello/hermann

###

GET http://localhost:8080/joke

###

GET https://icanhazdadjoke.com/
Accept: application/json

###

GET https://api.github.com/repos/lampepfl/dotty/contributors
